swagger: '2.0'
info:
  title: Simple Pet Store API (Swagger)
  version: '0.9.0'
host: api.example.com
basePath: /v2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  Pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
securityDefinitions:
  apiKey:
    type: apiKey
    name: X-API-KEY
    in: header
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPetsSwagger
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: A list of pets.
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
    post:
      summary: Create a pet
      operationId: createPetSwagger
      tags:
        - pets
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '201':
          description: Null response
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetByIdSwagger
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          type: string
      responses:
        '200':
          description: Information about the pet
          schema:
            $ref: '#/definitions/Pet'
